inherit_from: configs/Replica/replica.yaml
mapping:
  bound: [[-5.6,1.4],[-3.2,2.8],[-1.6,1.8]]
  marching_cubes_bound: [[-5.6,1.4],[-3.2,2.8],[-1.6,1.8]]
  keyframe_every: 1
  map_every: 1


mesh: 
  render_color: True
  vis: 60  


data:
  datadir: data/Replica/room1
  trainskip: 1
  output: output/Replica/room1
  exp_name: Udon
  load_path: trained_decoder.pt


tracking:
  gt_pose: True


multi_agents:
  num_agents: 3
  complete_graph: True
  edges_for_dropout: [ [0,1,0.5], [0,2,0.5], [1,2,0.5] ]
  distributed_algorithm: 'AUQ_CADMM'
  rho: 0.001
  track_uncertainty: True
  fix_decoder: True
  alpha: 0.9

edge_based: True